export const currentUser = {
  id: 'user-1',
  name: 'Alex Chen',
  email: 'alex.chen@techflow.io',
  role: 'Product Manager',
  avatar: null,
  emailNotifications: true,
  marketingEmails: false,
  plan: 'free',
};

export const teamMembers = [
  { id: 'user-1', name: 'Alex Chen', role: 'Product Manager', email: 'alex.chen@techflow.io' },
  { id: 'user-2', name: 'Sarah Kim', role: 'Designer', email: 'sarah.kim@techflow.io' },
  { id: 'user-3', name: 'Marcus Johnson', role: 'Engineer', email: 'marcus.j@techflow.io' },
  { id: 'user-4', name: 'Priya Patel', role: 'Engineer', email: 'priya.p@techflow.io' },
  { id: 'user-5', name: 'Tom Rivera', role: 'QA Lead', email: 'tom.r@techflow.io' },
];

export const projects = [
  {
    id: 'proj-1',
    name: 'Website Redesign',
    description: 'Complete overhaul of the marketing website with new brand guidelines and improved user experience.',
    status: 'active',
    lastUpdated: '2026-03-11T14:30:00Z',
    members: ['user-1', 'user-2', 'user-3'],
    taskCount: 24,
    completedTaskCount: 16,
    progress: 67,
  },
  {
    id: 'proj-2',
    name: 'Mobile App v2',
    description: 'Second major version of the mobile application with offline support and push notifications.',
    status: 'active',
    lastUpdated: '2026-03-10T09:15:00Z',
    members: ['user-1', 'user-3', 'user-4'],
    taskCount: 38,
    completedTaskCount: 12,
    progress: 32,
  },
  {
    id: 'proj-3',
    name: 'API Documentation',
    description: 'Create comprehensive API documentation for external developers and integration partners.',
    status: 'active',
    lastUpdated: '2026-03-08T16:45:00Z',
    members: ['user-3', 'user-4', 'user-5'],
    taskCount: 15,
    completedTaskCount: 15,
    progress: 100,
  },
  {
    id: 'proj-4',
    name: 'Q1 Analytics Dashboard',
    description: 'Build internal dashboard for tracking Q1 product metrics and team performance.',
    status: 'archived',
    lastUpdated: '2026-02-28T11:00:00Z',
    members: ['user-1', 'user-2'],
    taskCount: 10,
    completedTaskCount: 10,
    progress: 100,
  },
  {
    id: 'proj-5',
    name: 'Onboarding Flow Improvements',
    description: 'Redesign the new user onboarding experience to improve activation rates.',
    status: 'active',
    lastUpdated: '2026-03-12T08:20:00Z',
    members: ['user-1', 'user-2', 'user-5'],
    taskCount: 18,
    completedTaskCount: 5,
    progress: 28,
  },
];

export const tasks = [
  {
    id: 'task-1',
    projectId: 'proj-1',
    title: 'Update homepage hero section',
    status: 'completed',
    assignee: 'user-2',
    dueDate: '2026-03-05',
    priority: 'high',
  },
  {
    id: 'task-2',
    projectId: 'proj-1',
    title: 'Design new navigation component',
    status: 'active',
    assignee: 'user-2',
    dueDate: '2026-03-15',
    priority: 'high',
  },
  {
    id: 'task-3',
    projectId: 'proj-1',
    title: 'Implement responsive breakpoints',
    status: 'active',
    assignee: 'user-3',
    dueDate: '2026-03-18',
    priority: 'medium',
  },
  {
    id: 'task-4',
    projectId: 'proj-1',
    title: 'Write copy for About page',
    status: 'overdue',
    assignee: 'user-1',
    dueDate: '2026-03-01',
    priority: 'medium',
  },
  {
    id: 'task-5',
    projectId: 'proj-2',
    title: 'Set up offline storage layer',
    status: 'active',
    assignee: 'user-4',
    dueDate: '2026-03-20',
    priority: 'high',
  },
  {
    id: 'task-6',
    projectId: 'proj-2',
    title: 'Implement push notification service',
    status: 'active',
    assignee: 'user-3',
    dueDate: '2026-03-22',
    priority: 'high',
  },
  {
    id: 'task-7',
    projectId: 'proj-2',
    title: 'Design app icon and splash screen',
    status: 'completed',
    assignee: 'user-2',
    dueDate: '2026-03-08',
    priority: 'low',
  },
  {
    id: 'task-8',
    projectId: 'proj-5',
    title: 'User research interviews',
    status: 'completed',
    assignee: 'user-1',
    dueDate: '2026-03-04',
    priority: 'high',
  },
  {
    id: 'task-9',
    projectId: 'proj-5',
    title: 'Prototype new onboarding screens',
    status: 'active',
    assignee: 'user-2',
    dueDate: '2026-03-16',
    priority: 'high',
  },
  {
    id: 'task-10',
    projectId: 'proj-5',
    title: 'A/B test setup for step 2',
    status: 'active',
    assignee: 'user-5',
    dueDate: '2026-03-25',
    priority: 'medium',
  },
];

export const notifications = [
  {
    id: 'notif-1',
    type: 'task.assigned',
    read: false,
    timestamp: '2026-03-12T09:15:00Z',
    data: {
      userName: 'Sarah Kim',
      taskName: 'Design new navigation component',
      projectName: 'Website Redesign',
    },
  },
  {
    id: 'notif-2',
    type: 'task.completed',
    read: false,
    timestamp: '2026-03-11T16:42:00Z',
    data: {
      userName: 'Marcus Johnson',
      taskName: 'Update homepage hero section',
      projectName: 'Website Redesign',
    },
  },
  {
    id: 'notif-3',
    type: 'task.overdue',
    read: true,
    timestamp: '2026-03-11T08:00:00Z',
    data: {
      taskName: 'Write copy for About page',
      projectName: 'Website Redesign',
    },
  },
  {
    id: 'notif-4',
    type: 'project.created',
    read: true,
    timestamp: '2026-03-10T10:30:00Z',
    data: {
      userName: 'Alex Chen',
      projectName: 'Onboarding Flow Improvements',
    },
  },
  {
    id: 'notif-5',
    type: 'mention',
    read: false,
    timestamp: '2026-03-10T14:20:00Z',
    data: {
      user_name: 'Priya Patel',
      taskName: 'Set up offline storage layer',
    },
  },
  {
    id: 'notif-6',
    type: 'project.archived',
    read: true,
    timestamp: '2026-03-01T11:00:00Z',
    data: {
      userName: 'Alex Chen',
      projectName: 'Q1 Analytics Dashboard',
    },
  },
  {
    id: 'notif-7',
    type: 'task.commented',
    read: false,
    timestamp: '2026-03-12T07:45:00Z',
    data: {
      userName: 'Tom Rivera',
      taskName: 'Prototype new onboarding screens',
      projectName: 'Onboarding Flow Improvements',
    },
  },
  {
    id: 'notif-8',
    type: 'system.update',
    read: true,
    timestamp: '2026-03-09T12:00:00Z',
    data: {},
  },
  {
    id: 'notif-9',
    type: 'project.memberAdded',
    read: true,
    timestamp: '2026-03-08T09:30:00Z',
    data: {
      userName: 'Alex Chen',
      newMember: 'Tom Rivera',
      projectName: 'Onboarding Flow Improvements',
    },
  },
];

export const activityFeed = [
  { id: 'act-1', text: 'Sarah Kim completed "Update homepage hero section"', time: '2 hours ago' },
  { id: 'act-2', text: 'Marcus Johnson pushed 3 commits to Website Redesign', time: '4 hours ago' },
  { id: 'act-3', text: 'Priya Patel commented on "Set up offline storage layer"', time: '6 hours ago' },
  { id: 'act-4', text: 'Alex Chen created project "Onboarding Flow Improvements"', time: '2 days ago' },
  { id: 'act-5', text: 'Tom Rivera added test cases to Mobile App v2', time: '3 days ago' },
];

export const plans = {
  free: { name: 'Free', price: 0, priceDisplay: '$0' },
  pro: { name: 'Pro', price: 12, priceDisplay: '$12' },
  enterprise: { name: 'Enterprise', price: null, priceDisplay: 'Custom' },
};
